@auth0Domain = {{auth0Domain}}
@auth0Audience = {{auth0Audience}}
@clientId = {{clientId}}
@clientSecret = {{clientSecret}}

### Auth0 token (Client Credentials) -> stores access_token into global variable {{token}}
POST https://{{auth0Domain}}/oauth/token
Content-Type: application/json
Accept: application/json

{
  "client_id": "{{clientId}}",
  "client_secret": "{{clientSecret}}",
  "audience": "{{auth0Audience}}",
  "grant_type": "client_credentials"
}

> {%
  client.global.set("token", response.body.access_token);
%}
