@baseUrl = {{baseUrl}}
@token = {{token}}

### List all games (simplified)
GET {{baseUrl}}/games
Authorization: Bearer {{token}}
Accept: application/json

### Get a game by id
GET {{baseUrl}}/games/<gameId>
Authorization: Bearer {{token}}
Accept: application/json

### List games for a team
GET {{baseUrl}}/games/teamID/<teamId>
Authorization: Bearer {{token}}
Accept: application/json

### Play a game (simplified)
POST {{baseUrl}}/games/0d1fdbf8-a758-4620-9d90-41cee85579c7/play
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

### Schedule a game (creates GamePlans + Game + GameTimeEvent)
POST {{baseUrl}}/games/schedule
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "homeTeamId": "57f3cfc3-8118-41cf-aadb-a40a1b96595b",
  "awayTeamId": "1587b0c2-26b7-447b-8d0b-6aa7123e4828",
  "localDateTime": "2026-04-08T22:00:00",
  "zoneId": "Europe/Paris",
  "leagueSeasonId": "7598a44d-9218-4bcd-a6ac-b7288d01f8f0"
}

### Schedule a game (today 17:00 Dallas time)
POST {{baseUrl}}/games/schedule
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "homeTeamId": "46db2f6f-2add-41de-9df1-0521df96620d",
  "awayTeamId": "79b4b582-d1a9-4e3c-833f-11feb4b8348a",
  "localDateTime": "2026-04-07T17:00:00",
  "zoneId": "America/Chicago",
  "leagueSeasonId": "1d12d075-96a5-4412-900f-e4e6f5cb8562"
}
