@baseUrl = {{baseUrl}}
@token = {{token}}

### List all games (simplified)
GET {{baseUrl}}/games
Authorization: Bearer {{token}}
Accept: application/json

### Get a game by id
GET {{baseUrl}}/games/<gameId>
Authorization: Bearer {{token}}
Accept: application/json

### List games for a team
GET {{baseUrl}}/games/teamID/<teamId>
Authorization: Bearer {{token}}
Accept: application/json

### Play a game (simplified)
POST {{baseUrl}}/games/0d1fdbf8-a758-4620-9d90-41cee85579c7/play
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json