@baseUrl = {{baseUrl}}
@token = {{token}}

### List all players
GET {{baseUrl}}/players
Authorization: Bearer {{token}}
Accept: application/json

### Generate 100 random players
POST {{baseUrl}}/players/generate
Authorization: Bearer {{token}}
Accept: application/json

### Get a player by id
GET {{baseUrl}}/players/547d0ba9-bb95-4300-81ab-6237a838b1d2
Authorization: Bearer {{token}}
Accept: application/json

### Delete a player by id
DELETE {{baseUrl}}/players/<playerId>
Authorization: Bearer {{token}}
Accept: application/json

### Delete all players
DELETE {{baseUrl}}/players
### Remove a player from all teams (free agent)
DELETE {{baseUrl}}/players/f7e44bcd-b064-4655-80b2-1abb9ec58d90/teams
### Remove a player from all teams (free agent)
DELETE {{baseUrl}}/players/f7120c64-4bf9-4c5f-8f84-209642523a38/teams
Authorization: Bearer {{token}}
Accept: application/json
