@baseUrl = {{baseUrl}}
@token = {{token}}

### List all teams
GET {{baseUrl}}/teams
Authorization: Bearer {{token}}
Accept: application/json

### Get a team by id
GET {{baseUrl}}/teams/<teamId>
Authorization: Bearer {{token}}
Accept: application/json

### Create a player for a team (adds player to team_players)
POST {{baseUrl}}/teams/cd6d3d84-686c-4bda-90e4-34fcbbcdf9fa/players
Authorization: Bearer {{token}}
Content-Type: application/json
Accept: application/json

{
  "archetype": "TWO_POINT_SCORER"
}
