spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-csf1pz6vkgyyinsz.us.auth0.com/

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # dev only (prod: validate / none)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  cors:
    allowed-origins: "http://localhost:4201,https://allauch-basketball-simulator.onrender.com"
auth0:
  audience: https://allauch-simulator-backend/

logging:
  level:
    org.springframework.security: DEBUG
